"use client";

import { useState, useMemo, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table } from "@/components/Table/Table";
import { ColumnDef } from "@tanstack/react-table";
import { FieldSelectorDropdown } from "@/components/FieldSelectorDropdown";
import { PaginationControl } from "@/components/pagination";
import { useRouter } from "next/navigation";
import { Plus } from "lucide-react";
import { IoReorderThree } from "react-icons/io5";


type Bill = {
  id: string;
  billNo: string;
  caseId: string;
  date: string;
  patientName: string;
  generatedBy: string;
  doctorName: string;
  amount: number;
  discount: number;
  tax: number;
  netAmount: number;
  paidAmount: number;
  refundAmount: number;
  balanceAmount: number;
};

type TypedColumn<T> = ColumnDef<T> & { accessorKey?: string };

export default function PharmacyBillPage() {
  const [bills, setBills] = useState<Bill[]>([]);
  const [search, setSearch] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const [rowsPerPage, setRowsPerPage] = useState(10);
  const route = useRouter() ;
  const [visibleFields, setVisibleFields] = useState<string[]>([
    "billNo",
    "caseId",
    "date",
    "patientName",
    "doctorName",
    "amount",
    "netAmount",
  ]);

  useEffect(() => {
    const saved = localStorage.getItem("visibleBillFields");
    if (saved) setVisibleFields(JSON.parse(saved));
  }, []);

  useEffect(() => {
    localStorage.setItem("visibleBillFields", JSON.stringify(visibleFields));
  }, [visibleFields]);

  useEffect(() => {
    const mockData: Bill[] = [
      {
        id: "1",
        billNo: "B001",
        caseId: "C100",
        date: "2025-01-05",
        patientName: "Rahul Sharma",
        generatedBy: "Admin",
        doctorName: "Dr. Gupta",
        amount: 1200,
        discount: 100,
        tax: 50,
        netAmount: 1150,
        paidAmount: 1000,
        refundAmount: 0,
        balanceAmount: 150,
      },
    ];
    setBills(mockData);
  }, []);

  const filteredData = useMemo(() => {
    return bills.filter((b) =>
      search
        ? b.billNo.toLowerCase().includes(search.toLowerCase()) ||
          b.patientName.toLowerCase().includes(search.toLowerCase()) ||
          b.caseId.toLowerCase().includes(search.toLowerCase())
        : true
    );
  }, [search, bills]);

  const totalPages = Math.ceil(filteredData.length / rowsPerPage);
  const paginated = filteredData.slice(
    (currentPage - 1) * rowsPerPage,
    currentPage * rowsPerPage
  );

  const handlePrint = (bill: Bill) => {
    console.log("Print Bill:", bill);

  };

  const allColumns: ColumnDef<Bill>[] = [
    { accessorKey: "billNo", header: "Bill No" },
    { accessorKey: "caseId", header: "Case ID" },
    { accessorKey: "date", header: "Date" },
    { accessorKey: "patientName", header: "Patient Name" },
    { accessorKey: "generatedBy", header: "Generated By" },
    { accessorKey: "doctorName", header: "Doctor Name" },
    { accessorKey: "amount", header: "Amount" },
    { accessorKey: "discount", header: "Discount" },
    { accessorKey: "tax", header: "Tax" },
    { accessorKey: "netAmount", header: "Net Amount" },
    { accessorKey: "paidAmount", header: "Paid Amount" },
    { accessorKey: "refundAmount", header: "Refund" },
    { accessorKey: "balanceAmount", header: "Balance" },
    {
      id: "actions",
      header: "Actions",
      cell: ({ row }) => (
        <Button
          variant="outline"
          size="sm"
          onClick={() => handlePrint(row.original)}
        >
          Print
        </Button>
      ),
    },
  ];

  const columns = useMemo(() => {
    const filtered = allColumns.filter((col) => {
      if (col.id === "actions") return false; 

      const key = "accessorKey" in col ? col.accessorKey : undefined;
      return key && visibleFields.includes(key as string);
    });

    const actionCol = allColumns.find((c) => c.id === "actions");
    if (actionCol) filtered.push(actionCol);

    return filtered;
  }, [visibleFields, allColumns]);

  return (
    <div className="p-6">

      <h1 className="text-3xl font-bold mb-4">Pharmacy Bill</h1>

      <div className="flex justify-between items-center mb-4 flex-wrap gap-3">
        <Input
          placeholder="Search Bill / Patient / Case ID"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="max-w-sm"
        />

        <div className="flex gap-3">
          <Button variant="outline"><Plus size={16} /> Generate Bill</Button>
          <Button variant="outline" onClick={()=> route.push("/doctor/pharmacy/medicine")}><IoReorderThree size={16}/>Medicine</Button>

          <FieldSelectorDropdown
            columns={allColumns as TypedColumn<Bill>[]}
            visibleFields={visibleFields}
            onToggle={(key, checked) => {
              setVisibleFields((prev) =>
                checked ? [...prev, key] : prev.filter((f) => f !== key)
              );
            }}
          />
        </div>
      </div>

      
        <Table data={paginated} columns={columns} />


      <PaginationControl
        currentPage={currentPage}
        totalPages={totalPages}
        rowsPerPage={rowsPerPage}
        onPageChange={setCurrentPage}
        onRowsPerPageChange={(val) => {
          setRowsPerPage(val);
          setCurrentPage(1);
        }}
      />
    </div>
  );
}
