"use client";

import { useMemo, useState } from "react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  List,
  Search,
  FileText,
} from "lucide-react";
import { ColumnDef } from "@tanstack/react-table";
import { Table as DataTable } from "@/components/Table/Table";
import BackButton from "@/Components/BackButton";
/* ---------------- Types ---------------- */
interface DischargedPatient {
  id: string;
  name: string;
  patientId: string;
  caseId: string;
  gender: string;
  phone: string;
  generatedBy: string;
  consultantDoctor: string;
  admissionDate: string;
  dischargedDate: string;
  tax: string;
  netAmount: string;
  total: string;
}

/* ---------------- Dummy Data ---------------- */
const DUMMY_DATA: DischargedPatient[] = [
  {
    id: "1",
    name: "Ramesh Kumar",
    patientId: "P-1021",
    caseId: "CASE-2210",
    gender: "Male",
    phone: "9876543210",
    generatedBy: "Reception",
    consultantDoctor: "Dr. Amit Sharma",
    admissionDate: "12-02-2025",
    dischargedDate: "18-02-2025",
    tax: "₹1,200",
    netAmount: "₹18,800",
    total: "₹20,000",
  },
  {
    id: "2",
    name: "Sunita Devi",
    patientId: "P-1045",
    caseId: "CASE-2235",
    gender: "Female",
    phone: "9123456780",
    generatedBy: "OPD Desk",
    consultantDoctor: "Dr. Neha Gupta",
    admissionDate: "05-02-2025",
    dischargedDate: "11-02-2025",
    tax: "₹900",
    netAmount: "₹14,100",
    total: "₹15,000",
  },
];

/* ---------------- Page ---------------- */
export default function IPDDischargedPatientManager() {
  const [search, setSearch] = useState("");

  const filteredData = useMemo(() => {
    if (!search) return DUMMY_DATA;
    const s = search.toLowerCase();
    return DUMMY_DATA.filter((item) =>
      Object.values(item).some((val) =>
        val.toString().toLowerCase().includes(s)
      )
    );
  }, [search]);
  /* ---------- Columns ---------- */
const columns: ColumnDef<DischargedPatient>[] = [
  {
    accessorKey: "name",
    header: "Name",
    cell: ({ row }) => (
      <span className="font-medium">{row.original.name}</span>
    ),
  },
  { accessorKey: "patientId", header: "Patient ID" },
  { accessorKey: "caseId", header: "Case ID" },
  { accessorKey: "gender", header: "Gender" },
  { accessorKey: "phone", header: "Phone" },
  { accessorKey: "generatedBy", header: "Generated By" },
  { accessorKey: "consultantDoctor", header: "Consultant Doctor" },
  { accessorKey: "admissionDate", header: "Admission Date" },
  { accessorKey: "dischargedDate", header: "Discharged Date" },
  { accessorKey: "tax", header: "Tax" },
  { accessorKey: "netAmount", header: "Net Amount" },
  {
    accessorKey: "total",
    header: "Total",
    cell: ({ row }) => (
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger asChild>
            <div className="flex items-center justify-center gap-1 font-semibold text-indigo-600 cursor-pointer">
              {row.original.total}
              <FileText className="h-4 w-4 opacity-70 hover:opacity-100" />
            </div>
          </TooltipTrigger>
          <TooltipContent>View billing breakup</TooltipContent>
        </Tooltip>
      </TooltipProvider>
    ),
  },
];
  return (
    <div className="p-6 space-y-6 mt-4">
        <BackButton/>
      {/* HEADER */}
      <Card>
        <CardHeader className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <CardTitle className="text-2xl font-bold text-indigo-700 dark:text-white flex items-center gap-2">
            <List className="h-6 w-6 text-indigo-600" />
            IPD Discharged Patient
          </CardTitle>

          <div className="relative w-full sm:w-72">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search discharged patient..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-9"
            />
          </div>
        </CardHeader>
      </Card>

      {/* TABLE */}
      <Card className="shadow-md">
  <CardContent className="p-0">
    <DataTable
      data={filteredData}
      columns={columns}
      fallback="No discharged patients found"
    />
  </CardContent>
</Card>
    </div>
  );
}
