"use client";

import { useEffect, useState } from "react";
import { Table } from "@/components/Table/Table";
import { ColumnDef } from "@tanstack/react-table";
import { Input } from "@/components/ui/input";
import { PaginationControl } from "@/components/pagination";
import { FieldSelectorDropdown } from "@/components/FieldSelectorDropdown";
import { Button } from "@/components/ui/button";
import {
  Plus,
  List,
  Search,
  Users,
  Bed,
  Stethoscope,
} from "lucide-react";
import { useRouter } from "next/navigation";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

/* ---------- Types ---------- */
interface IPDPatient {
  ipdNo: string;
  caseId: string;
  name: string;
  gender: string;
  phone: string;
  generatedBy: string;
  consultantDoctor: string;
  bed: string;
  isAntenatal: boolean;
  previousMedicalIssue: string;
  creditLimit: string;
}

/* ---------- Dummy Data ---------- */
const DUMMY_IPD_PATIENTS: IPDPatient[] = [
  {
    ipdNo: "IPD-001",
    caseId: "CASE-1001",
    name: "Ramesh Kumar",
    gender: "Male",
    phone: "9876543210",
    generatedBy: "Reception",
    consultantDoctor: "Dr. Amit Sharma",
    bed: "Bed A-12",
    isAntenatal: false,
    previousMedicalIssue: "Diabetes",
    creditLimit: "₹50,000",
  },
  {
    ipdNo: "IPD-002",
    caseId: "CASE-1002",
    name: "Sunita Devi",
    gender: "Female",
    phone: "9123456780",
    generatedBy: "OPD Desk",
    consultantDoctor: "Dr. Neha Gupta",
    bed: "Bed B-05",
    isAntenatal: true,
    previousMedicalIssue: "Anemia",
    creditLimit: "₹75,000",
  },
];

/* ---------- Page ---------- */
export default function IPDPatientListPage() {
  const [allData, setAllData] = useState<IPDPatient[]>([]);
  const [filteredData, setFilteredData] = useState<IPDPatient[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const route = useRouter();

  const [currentPage, setCurrentPage] = useState(1);
  const [rowsPerPage, setRowsPerPage] = useState(20);
  const [visibleFields, setVisibleFields] = useState<string[]>([
    "gender",
    "phone",
    "consultantDoctor",
    "creditLimit",
  ]);

  useEffect(() => {
    setTimeout(() => {
      setAllData(DUMMY_IPD_PATIENTS);
      setLoading(false);
    }, 600);
  }, []);

  useEffect(() => {
    let data = [...allData];
    if (search.trim()) {
      const s = search.toLowerCase();
      data = data.filter((item) =>
        Object.values(item).some((val) =>
          val?.toString().toLowerCase().includes(s)
        )
      );
    }
    setFilteredData(data);
    setCurrentPage(1);
  }, [allData, search]);

  /* ---------- Columns ---------- */
  const fixedColumns: ColumnDef<IPDPatient>[] = [
    {
      accessorKey: "ipdNo",
      header: "IPD No",
      cell: ({ row }) => (
        <button
          onClick={() =>
            route.push(`/doctor/IPD/ipdDetails/${row.original.ipdNo}/ipd`)
          }
          className="font-semibold text-overview-base hover:text-indigo-400 underline cursor-pointer"
        >
          {row.original.ipdNo}
        </button>
      ),
    },
    { accessorKey: "caseId", header: "Case ID" },
    { accessorKey: "name", header: "Patient Name" },
  ];

  const optionalColumns: ColumnDef<IPDPatient>[] = [
    { accessorKey: "gender", header: "Gender" },
    { accessorKey: "phone", header: "Phone" },
    { accessorKey: "generatedBy", header: "Generated By" },
    { accessorKey: "consultantDoctor", header: "Consultant Doctor" },
    { accessorKey: "bed", header: "Bed" },
    {
      accessorKey: "isAntenatal",
      header: "Antenatal",
      cell: ({ row }) =>
        row.original.isAntenatal ? (
          <span className="text-green-600 font-medium">Yes</span>
        ) : (
          <span className="text-gray-500">No</span>
        ),
    },
    { accessorKey: "previousMedicalIssue", header: "Medical Issue" },
    { accessorKey: "creditLimit", header: "Credit Limit" },
  ];

  const displayedOptionalCols = optionalColumns.filter(
    (col): col is ColumnDef<IPDPatient, any> & {
      accessorKey: keyof IPDPatient;
    } =>
      "accessorKey" in col &&
      visibleFields.includes(col.accessorKey as string)
  );

  const columns = [...fixedColumns, ...displayedOptionalCols];

  const totalPages = Math.ceil(filteredData.length / rowsPerPage);
  const paginatedData = filteredData.slice(
    (currentPage - 1) * rowsPerPage,
    currentPage * rowsPerPage
  );

  return (
    <div className="p-6 space-y-6">
      {/* ---------- HEADER CARD ---------- */}
      <Card className="bg-Module-header text-white shadow-lg">
        <CardHeader className="flex flex-col sm:flex-row justify-between gap-4">
          <div>
            <CardTitle className="text-3xl flex items-center gap-2">
              <Users className="h-7 w-7" />
              IPD Patient List
            </CardTitle>
            <p className="text-sm text-indigo-100 mt-1">
              Manage admitted patients & bed allocations
            </p>
          </div>

          <div className="flex gap-2 flex-wrap">
            <Button
              onClick={() => route.push("/doctor/IPD/registration")}
              className="bg-white text-indigo-700 hover:bg-indigo-50"
            >
              <Plus className="h-4 w-4 mr-1" />
              Add Patient
            </Button>
            <Button
              variant="outline"
              className="border-white text-foreground"
              onClick={()=>route.push("/doctor/IPD/dischargedPatients")}
            >
              <List className="h-4 w-4 mr-1" />
              Discharged
            </Button>
          </div>
        </CardHeader>
      </Card>

      {/* ---------- FILTER BAR ---------- */}
      <Card className="bg-overview-card border-overview-strong">
        <CardContent className="p-4 flex flex-wrap items-center gap-3">
          <div className="relative">
            <Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search patients..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-9 w-64"
            />
          </div>

          <FieldSelectorDropdown
            columns={optionalColumns as any}
            visibleFields={visibleFields}
            onToggle={(key, checked) =>
              setVisibleFields((prev) =>
                checked ? [...prev, key] : prev.filter((f) => f !== key)
              )
            }
          />
        </CardContent>
      </Card>

      {/* ---------- TABLE ---------- */}
      {/* <Card className="shadow-md bg-overview-card border-overview-strong">
        <CardContent className="p-0"> */}
          {loading ? (
            <div className="h-[300px] flex items-center justify-center text-lg font-medium animate-pulse">
              Loading patients...
            </div>
          ) : (
            <>
              <Table
                data={paginatedData}
                columns={columns}
                fallback="No patients found"
                headerTextClassName="text-dialog-icon"
                bodyTextClassName="text-overview-muted"
              />
              <PaginationControl
                currentPage={currentPage}
                totalPages={totalPages}
                rowsPerPage={rowsPerPage}
                onPageChange={setCurrentPage}
                onRowsPerPageChange={(val) => {
                  setRowsPerPage(val);
                  setCurrentPage(1);
                }}
              />
            </>
          )}
        {/* </CardContent>
      </Card> */}
    </div>
  );
}
