"use client";

import { useEffect, useState } from "react";
import { Table } from "@/components/Table/Table";
import { ColumnDef } from "@tanstack/react-table";
import { Input } from "@/components/ui/input";
import { PaginationControl } from "@/components/pagination";
import { FieldSelectorDropdown } from "@/components/FieldSelectorDropdown";
import { Button } from "@/components/ui/button";
import { Plus, List } from "lucide-react";
import { useRouter } from "next/navigation";

interface IPDPatient {
  ipdNo: string;
  caseId: string;
  name: string;
  gender: string;
  phone: string;
  generatedBy: string;
  consultantDoctor: string;
  bed: string;
  isAntenatal: boolean;
  previousMedicalIssue: string;
  creditLimit: string;
}

const DUMMY_IPD_PATIENTS: IPDPatient[] = [
  {
    ipdNo: "IPD-001",
    caseId: "CASE-1001",
    name: "Ramesh Kumar",
    gender: "Male",
    phone: "9876543210",
    generatedBy: "Reception",
    consultantDoctor: "Dr. Amit Sharma",
    bed: "Bed A-12",
    isAntenatal: false,
    previousMedicalIssue: "Diabetes",
    creditLimit: "₹50,000",
  },
  {
    ipdNo: "IPD-002",
    caseId: "CASE-1002",
    name: "Sunita Devi",
    gender: "Female",
    phone: "9123456780",
    generatedBy: "OPD Desk",
    consultantDoctor: "Dr. Neha Gupta",
    bed: "Bed B-05",
    isAntenatal: true,
    previousMedicalIssue: "Anemia",
    creditLimit: "₹75,000",
  },
  {
    ipdNo: "IPD-003",
    caseId: "CASE-1003",
    name: "Amit Verma",
    gender: "Male",
    phone: "9988776655",
    generatedBy: "Emergency",
    consultantDoctor: "Dr. Rajesh Singh",
    bed: "ICU-02",
    isAntenatal: false,
    previousMedicalIssue: "Hypertension",
    creditLimit: "₹1,00,000",
  },
  {
    ipdNo: "IPD-004",
    caseId: "CASE-1004",
    name: "Pooja Mehta",
    gender: "Female",
    phone: "9090909090",
    generatedBy: "Reception",
    consultantDoctor: "Dr. Kavita Rao",
    bed: "Bed C-10",
    isAntenatal: true,
    previousMedicalIssue: "None",
    creditLimit: "₹60,000",
  },
  {
    ipdNo: "IPD-005",
    caseId: "CASE-1005",
    name: "Suresh Yadav",
    gender: "Male",
    phone: "9812345678",
    generatedBy: "OPD Desk",
    consultantDoctor: "Dr. Manish Jain",
    bed: "Bed D-03",
    isAntenatal: false,
    previousMedicalIssue: "Asthma",
    creditLimit: "₹40,000",
  },
];

export default function IPDPatientListPage() {
  const [allData, setAllData] = useState<IPDPatient[]>([]);
  const [filteredData, setFilteredData] = useState<IPDPatient[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const route = useRouter();
  const [currentPage, setCurrentPage] = useState(1);
  const [rowsPerPage, setRowsPerPage] = useState(20);
  const [visibleFields, setVisibleFields] = useState<string[]>([
    "gender",
    "phone",
    "consultantDoctor",
    "creditLimit",
  ]);

  // Fetch patients
  const fetchPatients = async () => {
  setLoading(true);

  setTimeout(() => {
    setAllData(DUMMY_IPD_PATIENTS);
    setLoading(false);
  }, 600); 
};


  useEffect(() => {
    fetchPatients();
  }, []);

  // Filter by search
  useEffect(() => {
    let data = [...allData];
    if (search.trim()) {
      const s = search.toLowerCase();
      data = data.filter((item) =>
        Object.values(item).some((val) =>
          val?.toString().toLowerCase().includes(s)
        )
      );
    }
    setFilteredData(data);
    setCurrentPage(1);
  }, [allData, search]);

  // Table columns
  const fixedColumns: ColumnDef<IPDPatient>[] = [
    {
    accessorKey: "ipdNo",
    header: "IPD No",
    cell: ({ row }) => {
        const ipdNo = row.original.ipdNo;

        return (
            <button
            onClick={() => route.push(`/doctor/IPD/ipdDetails/${ipdNo}/ipd`)}
            className="text-primary underline font-medium hover:text-primary/80"
            >
            {ipdNo}
            </button>
        );
        },
    },
    { accessorKey: "caseId", header: "Case ID" },
    { accessorKey: "name", header: "Name" },
  ];

  const optionalColumns: ColumnDef<IPDPatient>[] = [
    { accessorKey: "gender", header: "Gender" },
    { accessorKey: "phone", header: "Phone" },
    { accessorKey: "generatedBy", header: "Generated By" },
    { accessorKey: "consultantDoctor", header: "Consultant Doctor" },
    { accessorKey: "bed", header: "Bed" },
    {
      accessorKey: "isAntenatal",
      header: "Is Antenatal",
      cell: ({ row }) => (row.original.isAntenatal ? "Yes" : "No"),
    },
    { accessorKey: "previousMedicalIssue", header: "Previous Medical Issue" },
    { accessorKey: "creditLimit", header: "Credit Limit" },
  ];

  const displayedOptionalCols = optionalColumns.filter(
    (col): col is ColumnDef<IPDPatient, any> & { accessorKey: keyof IPDPatient } =>
      "accessorKey" in col && visibleFields.includes(col.accessorKey as string)
  );

  const columns = [...fixedColumns, ...displayedOptionalCols];

  const totalPages = Math.ceil(filteredData.length / rowsPerPage);
  const paginatedData = filteredData.slice(
    (currentPage - 1) * rowsPerPage,
    currentPage * rowsPerPage
  );

  return (
    <div className="bg-background text-foreground min-h-screen p-6">
      <div className="flex flex-wrap justify-between items-center gap-4 mb-6">
        <div>
          <h3 className="text-3xl font-bold text-gray-800 dark:text-gray-100">
            IPD Patient List
          </h3>
          <p className="text-sm text-gray-600 dark:text-gray-400">
            View and manage IPD patients efficiently
          </p>
        </div>

        <div className="flex gap-2 flex-wrap items-center">
          <Button
            variant="default"
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white dark:bg-none dark:text-inherit dark:hover:bg-none"
            onClick={() => route.push("/doctor/IPD/registration")}
          >
            <Plus className="w-4 h-4" /> Add Patient
          </Button>
          <Button
            variant="outline"
          >
            <List className="w-4 h-4" /> Discharged Patient
          </Button>
        </div>
        
      </div>
      <div className="flex flex-wrap gap-2 mb-6 items-center">
        <Input
          placeholder="Search by any field..."
          className="w-64"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <FieldSelectorDropdown
          columns={optionalColumns as any}
          visibleFields={visibleFields}
          onToggle={(key, checked) => {
            setVisibleFields((prev) =>
              checked ? [...prev, key] : prev.filter((f) => f !== key)
            );
          }}
        />
      </div>
      <div className="mt-6 text-sm">
        {loading ? (
          <p className="h-[400px] flex justify-center items-center text-lg font-medium animate-pulse">
            Loading patients...
          </p>
        ): (
          <>
            <Table data={paginatedData} columns={columns} fallback="No patients found" />
            <PaginationControl
              currentPage={currentPage}
              totalPages={totalPages}
              rowsPerPage={rowsPerPage}
              onPageChange={setCurrentPage}
              onRowsPerPageChange={(val) => {
                setRowsPerPage(val);
                setCurrentPage(1);
              }}
            />
          </>
        )}
      </div>
    </div>
  );
}

